### ISSUE TITLE
Update to cargo 0.22

### ISSUE THREAD

**Issue by debris** [roblabla/cargo-travis#18]
Is there eta when to expect update of this crate to `cargo 0.22`? currently running coverage on a project with a virtual workspace results in an error:

```
error: manifest path `/home/travis/build/paritytech/ethabi/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

this has been fixed in the latest cargo

**Comment by roblabla** [comment]
There's a port to cargo 0.21 in the PR queue that I never got around to merging. I'll try to use it to bring cargo-travis to the latest cargo version tomorrow.

**Comment by debris** [comment]
great, thanks!

**Comment by roblabla** [comment]
So I looked around, and `cargo 0.22` is a nightly version, and as such is unreleased on crates.io. I'm currently playing around with it, but it'll all go in a branch until cargo 0.22 is on crates.io.

**Comment by roblabla** [comment]
So `cargo 0.22` isn't released on crates.io for some reason. It's a bit of a pain, I'll try to figure out why is that. In the meantime, I'll use a git dependency, but I probably won't merge it into master until I can use cargo from crates.io.

**Comment by roblabla** [comment]
Tracking https://github.com/rust-lang/cargo/issues/4621

**Comment by roblabla** [comment]
So cargo 0.22 is now on crates.io (as usual, congrats to the rust devs for being super responsive \o/), and I managed to get something that seems to be working. @debris  Could you try to use

`cargo install --git https://github.com/roblabla/cargo-travis --branch cargo22`

in your `travis.yml` and make sure it works as expected ? If it does, I'll package it up and release :).

**Comment by debris** [comment]
it failed with the same error message

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: manifest path `/home/travis/build/paritytech/ethabi/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspac
```

link: https://travis-ci.org/paritytech/ethabi/builds/288567062?utm_source=github_status&utm_medium=notification

I guess that virtual workspace needs to be started with different params than a normal workspace

**Comment by debris** [comment]
you are right! now it works

https://travis-ci.org/paritytech/ethabi/builds/288577859

**Comment by roblabla** [comment]
Fixed in release 0.0.6

**Comment by debris** [comment]
thanks!

**Comment by debris** [comment]
just one more question. The crate is working fine for me at ethabi repo, but I have problems with the other repo, which has slightly different project structure. 

pr: https://github.com/debris/tiny-keccak/pull/19
coveralls report: https://coveralls.io/builds/13753308

coveralls reports that no files were covered
