### ISSUE TITLE
Upload docs to github pages

### ISSUE THREAD

**Issue by gnzlbg** [roblabla/cargo-travis#22]
Currently there doesn't seem to be an easy way to upload the docs to github pages.

**Comment by roblabla** [comment]
When I ported the tool, I was mostly after the code coverage bits. There are existing tools doing doc uploading very well.

PRs welcome, but I won't pursue this myself.

**Comment by gnzlbg** [comment]
> How do we want to structure gh-pages?
I have my build set up to delete everything in the branch (except index.html)

We should make this easy but we shouldn't delete stuff by default, so this should be an option.

> Then copy over target/doc/* to the branch root, 

I would prefer if the command would work on a `gh_pages_deploy` directory or similar. Maybe we should set it by default to point at `target/doc/*` but users should be able to customize it. 

For example, it is often useful to generate docs for multiple targets. I'd like the command to support doing that (e.g. we can add a test to generate docs for MacOS, Linux, Windows, ARM and x86).

The way people do this is to run rustdoc for each target, and then copy the docs into a single directory and upload that. The main doc page then contains links to the different targets. The `stdsimd` crate and the libc crates do this:

https://github.com/rust-lang-nursery/stdsimd/blob/master/ci/dox.sh

> then commit and push (which git eats if nothing changed). index.html is a manually added redirect HTML page to one of the crates' index page.

This sounds good.

> Make a new folder in root with the commit hash of the commit, and commit changes in there. I'd still recommend deleting the old one if it exists (for example, cron builds) in order to clean up if rustdoc output changes drastically.
Make a new folder for each branch. So you'd have user.github.io/repo/master/ for the master branch, and so on.
Above, but also do tags. Probably the best approach.

Yes something like this :)

**Comment by roblabla** [comment]
Travis also has a GITHUB_PAGES deploy target: https://docs.travis-ci.com/user/deployment/pages/. I don't really mind which approach is chosen, it's just an alternative ;).

**Comment by CAD97** [comment]
@roblabla I knew Travis had support for a deploy to gh-pages, I just couldn't find it when I was making that info dump. Unfortunately, I don't think it has the control that we would want for good directory structure (though feel free to prove me wrong), so I think I'm going to go the manual route.

@gnzlbg OK, I think I get the desired approach here. Here's the basic workflow I'm seeing:

.travis.yml
```
script:
  - |
    cargo build --verbose &&
    cargo test --verbose &&
    cargo doc --verbose # and whatever documentation targets you want to generate
after_success:
  - cargo doc-upload
```

`cargo-doc-upload` would then do the equivalent(ish) of the following almost-sh:

```sh
if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then
    git clone --branch gh-pages --depth=1 git@github.com:$TRAVIS_REPO_SLUG ./target/doc-upload
    cd ./target/doc-upload
    ls ./$TRAVIS_BRANCH | grep --invert-match "index.html" | xargs --verbose rm -r
    mv -f ../doc ./$TRAVIS_BRANCH
    git add -vA
    git commit -vm "Automatic CI documentation build"
    git push origin gh-pages
    cd ../..
fi
```

Customization:

- Branches that get uploaded
- `--token $GH_TOKEN` to use a GitHub token (made secure with CI secure env vars), otherwise assumes ssh git endpoint will work
- Commit message

**Comment by CAD97** [comment]
🎉 got it working: https://gist.github.com/CAD97/022e4fd3a0ca67fa6f4799b454a155d3

https://github.com/CAD97/test/tree/gh-pages

Working on the command line interface now, then I'll send a PR. Once the PR is up, I'll see if it's possible for me to try it out actually on Travis. (Does anyone know how to `cargo-install` direct from a git repository?)
