### ISSUE TITLE
No subcommand doc-upload

### ISSUE THREAD

**Issue by gnzlbg** [roblabla/cargo-travis#28]
I am getting errors when trying to use doc-upload: https://api.travis-ci.org/v3/job/330512048/log.txt

**Comment by CAD97** [comment]
Sorry for the confusion; I added this functionality this week and the version including doc-upload isn't published to crates.io yet.

Until the new version is uploaded, you can use a Git install: `cargo install crate-name --git repo`.

**Comment by roblabla** [comment]
Should be published.

**Comment by gnzlbg** [comment]
Ah sorry my fault! I just didn’t gave it enough thought
