### ISSUE TITLE
Update to newer version of Cargo

### ISSUE THREAD

**Issue by dragostis** [roblabla/cargo-travis#3]
Newer version of Cargo is needed for [proc-macro](https://doc.rust-lang.org/book/procedural-macros.html) crates.

**Comment by roblabla** [comment]
On it. I'm updating to 0.16

**Comment by dragostis** [comment]
Awesome! Thank you for maintaining this. :)

**Comment by roblabla** [comment]
0.0.3 has a newer version.

**Comment by dragostis** [comment]
Thanks a lot. Is there a way to run coveralls for two projects in the same repo?

**Comment by roblabla** [comment]
What's the repo like ? coveralls need to be run next to a Cargo.toml file.

**Comment by dragostis** [comment]
It's [this repo](https://github.com/dragostis/pest). I have two crates, `pest` and `pest_derive`.

**Comment by roblabla** [comment]
You should be able to just cd into each folder and run the commands twice.
