### ISSUE TITLE
kcov currently broken on travis for non-sudo builds

### ISSUE THREAD

**Issue by Arzte** [roblabla/cargo-travis#32]
Seems to have been caused by meltdown patches. https://github.com/travis-ci/travis-ci/issues/9061 Can been seen in the latest build of cargo-travis https://travis-ci.org/roblabla/cargo-travis/jobs/330593300#L2014

**Comment by roblabla** [comment]
Sadly, I'm afraid there isn't much we can do on our side besides updating the documentation to mention the `sudo: true` requirements :(.

**Comment by CAD97** [comment]
There's not much we can do about it, except maybe check `$TRAVIS_SUDO` and give a warning about Travis/#9061. As far as I can tell from discussion of the change, the disabling of personality on `sudo: false` builds is intentional and effectively final.
