### ISSUE TITLE
Kcov isn't being exucted

### ISSUE THREAD

**Issue by Arzte** [roblabla/cargo-travis#33]
Possibly this is related to #15, it only seems to occur with ``cargo coveralls --all``. Here's a failing build:
https://travis-ci.org/rust-av/rust-av/jobs/334260229#L1378
(Above build is part of https://github.com/rust-av/rust-av/pull/44)

**Comment by Coding-Doctors** [comment]
So looks like the issue isn't related to all the tests not running on the build that coveralls is ran on, but rather something a bit different. I'm out of ideas as to what might be causing this, here's a log. https://travis-ci.org/rust-av/rust-av/jobs/337067927#L1494
