### ISSUE TITLE
Version number in master is lower than on crates.io

### ISSUE THREAD

**Issue by hcpl** [roblabla/cargo-travis#39]
Crates.io has the 0.0.9 version published, but Cargo.toml in `master` [points to 0.0.8](https://github.com/roblabla/cargo-travis/blob/1b89cd70cd2bb69facbd8b3b77e9670af781282d/Cargo.toml#L3).

Could you push the changes and according tags, please?

**Comment by roblabla** [comment]
Forgot to push the release commit. Thanks for the heads up, fixed it :).
