### ISSUE TITLE
Coverage fails with 2018 edition

### ISSUE THREAD

**Issue by hntd187** [roblabla/cargo-travis#51]
I'm not exactly sure what is happening here, but it looks like doing a cargo update and then doing coverage in our CI build is broken by a dependency update. I can't tell if it's cargo-travis or our build somehow breaking it.

https://travis-ci.org/toshi-search/Toshi/jobs/471994844#L1634

**Comment by roblabla** [comment]
This is due to cargo-travis using a very old version of cargo-as-a-library.

**Comment by roblabla** [comment]
Permanent fix would be #52. In the meantime, I'll update the cargo dependency.

**Comment by roblabla** [comment]
Fixed with #54

**Comment by roblabla** [comment]
0.0.10 fixes this.
