### ISSUE TITLE
kcov gets built twice

### ISSUE THREAD

**Issue by dragostis** [roblabla/cargo-travis#6]
There's probably no reason for [this](https://travis-ci.org/pest-parser/pest/builds/206124907) to happen.

**Comment by roblabla** [comment]
Well, we build kcov locally. I guess I could build kcov in a global location, but that seems error prone. Maybe I could add a `--kcov-build-location` flag ?

**Comment by dragostis** [comment]
Location flag seems great. Would it then figure out that kcov was already built in that location? Or will it need another flag?

**Comment by roblabla** [comment]
It would figure if it's already built if it can find the binary there.

**Comment by dragostis** [comment]
Sounds like a good solution. 😃

**Comment by roblabla** [comment]
I'll implement it this week-end. Need some sleep for now :).
