### ISSUE TITLE
cargo doc-upload reports "already up-to-date" after auth failure

### ISSUE THREAD

**Issue by petr-tik** [roblabla/cargo-travis#62]
Hey, thanks for making such a cool cargo plugin. We use it at [tantivy](https://github.com/tantivy-search/tantivy/) to auto-update docs for the searcher/indexer library that we are developing. 

I was reviewing the [travis log from our recent build](https://api.travis-ci.org/v3/job/544505108/log.txt) and noticed an inconsistency between the authentication error and the last thing printed by doc-upload

```bash
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/tantivy-search/tantivy.git/'
Documentation already up-to-date.
```

I think the last line is from

https://github.com/roblabla/cargo-travis/blob/320fcac953b17e9a19dd0515216ae7a9fd2da36e/src/lib.rs#L367

The if/else logic implies that if documentation wasn't successfully updated, it must be already up to date, instead of reporting an error.

In our case, we had an authentication error, which prevented us from updating documentation. 

I think we should parse and log the exit status of the command, so logs can show people the real reason for failure. 

Will it help if I send a PR or are you too busy to review?

**Comment by roblabla** [comment]
🤔 so I just checked, and `git push origin master` returns 0 if the remote is already up to date. There's no reason to ignore the errors here - we should be bubbling them up. Replacing the custom logic here with a simple `require_success()` is probably the proper way forward. Feel free to open a PR.

**Comment by petr-tik** [comment]
When you say bubbling them up - do you mean just println'ing more details to stdout or doing something else?
